dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
compiler:
  solc:
    version: 0.8.9
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0"
networks:
  default: development
  rinkeby:
    nu_token: '0x78D591D90a4a768B9D2790deA465D472b6Fe0f18'
    nu_token_supply: 1_000_000_000
    t_staking: '0x18eFb520dA5D387982C860a64855C14C0AcADF3F'
    work_lock: '0x0000000000000000000000000000000000000000'
    verify: True
  mainnet:
    nu_token: '0x4fE83213D56308330EC302a8BD641f1d0113A4Cc'
    t_staking: '0x01B67b1194C75264d06F808A921228a95C765dd7'
    work_lock: '0xe9778E69a961e64d3cdBB34CF6778281d34667c2'
    verify: True
  development:
    nu_token_supply: 1_000_000_000
    verify: False